'use client';
import Head from "next/head";
import Link from "next/link";
import { useDisclosure } from '@mantine/hooks';
import { useSession, signIn, signOut } from "next-auth/react";
import { CollapseDesktop } from "@/components/desktop/CollapseDesktop";
import { MobileNavbar } from "@/components/desktop/MobileNavbar";
export default function Home() { 
  const [opened, { toggle }] = useDisclosure();
  const { data: session } = useSession()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <>
        {session? <CollapseDesktop/>:<MobileNavbar/>}
      </>
      </main>
      </>
  );
}
